import Head from 'next/head'
import About from '../components/About'
import Layout from '../components/Layout'
import Services from '../components/Services'
import css from '../styles/Home.module.css'

export default function Details () {
  return (
    <Layout>

       <div className={css.container}>
      <Head>
        <title>Rhevox</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* body */}
      <main>
        <About/>
        <Services/>
      </main>
    </div>

    </Layout>
   
  )
}
