import Head from 'next/head'
import Navbar from '../components/navbar'
import styles from '../styles/Home.module.css'

function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
        <h1> About Page </h1>
    </div>
  )
}
export default About