import Link from "next/link"
import { useRouter } from 'next/router'
import Head from 'next/head'
import Navbar from '../components/navbar'
import styles from '../styles/Home.module.css'
import Image from 'next/image'


function bookPage() { const router = useRouter()
  const handleClick = () => {

     console.log('cumpara cartea')
     router.push()
  }
  return (
    
    <div className={styles.container}>
      <Head>
        <title>Gaidos Semida</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.mainBook}>
        <h1 className={styles.title}> Books </h1>
        <div className={styles.imageBook}>
          {/* <Image
            src={"/bbl.jpg"}
            alt="carte"
            width={200}
            height={200}
          />
          <Image
            src={"/bbl.jpg"}
            alt="carte"
            width={200}
            height={200}
          />
          <Image
            src={"/bbl.jpg"}
            alt="carte"
            width={200}
            height={200}
          /> */}
        </div>
        <div className={styles.grid}>
        <h3> <p>10+ CELE MAI INFLUENTE CARTI DE DEZVOLTARE PERSONALA SI MOTIVATIE</p></h3>
        <h2>  1. „Puterea prezentului”, Eckhart Tolle </h2>
        <p > <h2> „Puterea prezentului” (The Power of Now) este un ghid pentru iluminarea spirituala. Va ofera cateva idei de aur cu privire la ceea ce inseamna cu adevarat a fi prezent. Aceasta carte explica intr-un mod extrem de accesibil, practic care este cheia pentru a experimenta mai multa bucurie in viata, aici si acum. Nu este de mirare ca aceasta carte in toata lumea si a fost tradusa in peste 30 de limbi straine.</h2></p>
        <Image
            src={"/tolle.jpg"}
            alt="carte"
            width={400}
            height={600}
          />
      </div>
        <button>
          <a href="https://event.2performant.com/events/click?ad_type=quicklink&amp;aff_code=d6df23165&amp;unique=9a6f02fef&amp;redirect_to=https%253A%252F%252Fwww.libris.ro%252Fputerea-prezentului-ed-6-eckhart-tolle-CVE978-606-588-858-6--p995781.html%253Fgclid%253DCjwKCAjwhOyJBhA4EiwAEcJdcc6GICErS73kTJnaVPG4FMqa3VUaMJ-q4rQsBw4opDCKaDCBBdnxexoCCZUQAvD_BwE">Cumpara „Puterea prezentului”, Eckhart Tolle»</a>
          </button>
          <div className={styles.grid}>
         <h2> 2. „Secretele succesului”, Dale Carnegie una dintre cele mai influente carti dezvoltare personala din istorie
          <p> Peste 15 milioane de exemplare au fost vandute in toata lumea, ceea ce o face una dintre cele mai vandute carti din toate timpurile.</p></h2>
          <Image
            src={"/ssc.webp"}
            alt="carte"
            width={400}
            height={600}
          />
           </div>
      </main>
    </div>
  )
}
export default bookPage