import Head from 'next/head'
import Navbar from '../components/navbar'
import styles from '../styles/Home.module.css'
import Validate from './Validate'

export default function contact () {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gaidos Semida</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
     < h1 className="display-3 text-center mt-5">Formular de contact</h1>
        <Validate/>
    
          </main>
    </div>
  )
}
