import Head from 'next/head'
import Info from '../components/Info'
import Layout from '../components/Layout'
import Products from '../components/Products'
import Services from '../components/Services'
import css from '../styles/Home.module.css'

export default function Home() {
  return (
    <Layout>

       <div className={css.container}>
      <Head>
        <title>Rhevox</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* body */}
      <main>
        <Info/>
        <Services/>
        <Products/>
      </main>
    </div>

    </Layout>
   
  )
}
