import Head from 'next/head'
import Layout from '../components/Layout'
import styles from '../styles/Header.module.css'

export default function Home() {
  return (
    <Layout>
       <div className={styles.container}>
      <Head>
        <title>Rhevox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* body */}
      <main>
        <h1>Subscribe to Rhevox</h1>
      </main>
    </div>

    </Layout>
   
  )
}
