import css from '../styles/Home.module.css'
import Head from 'next/head'
import Info from '../components/Info'
import Layout from '../components/Layout'
import Section1 from '../components/Section1'
import Section2 from '../components/Section2'
import Location from '../components/Location'

export default function Home() {
  return (
    <Layout>

       <div className={css.container}>
      <Head>
        <title>Rhevox</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* body */}
      <main>
        <Info/>
        <Section1/>
        <Section2/>
        <Location/>
      </main>
    </div>

    </Layout>
   
  )
}
