import Link from "next/link"
import { useRouter } from 'next/router'
import Head from 'next/head'
import Navbar from '../components/navbar'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'
import Image from 'next/image'


function skinPage() {

   const router = useRouter()
   const handleClick = () => {

      console.log('vezi produsul')
      router.push('/product')
   }

   return (

      <div className={styles.container}>
         <Head>
            <title>Semida Gaidos</title>
            <meta name="description" content="Generated by create next app" />
         </Head>
         <Navbar />

         <h1 className={styles.title}> Ingrijirea Tenului</h1>
         <h2> <Link href="/product" >
            <a>Products</a>
         </Link>
         </h2>
         <div className={styles.cosmetic}>
            <Image
               src={"/face.jpg"}
               alt="Picture of skin"
               width={500}
               height={500}

            />
            <h3><p>Fii la curent cu tendințele de frumusețe. Sfaturi și trucuri pentru aspectul tenului tau!  <button onClick={handleClick} >
               Vezi Produsuele
            </button> </p></h3>
            <Image
               src={"/skin.jpg"}
               alt="Picture of skin"
               width={500}
               height={500}
            />
         </div>
      </div>
   )
}
export default skinPage