import Head from 'next/head'
import Layout from '../components/Layout'
import css from '../styles/Home.module.css'

export default function Form () {
  return (
    <Layout>

       <div className={css.container}>
      <Head>
        <title>Rhevox</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* body */}
      <main>
      </main>
    </div>

    </Layout>
   
  )
}